### ISSUE TITLE
undefined is not an object (evaluating 'FBLoginManager.Events')

### ISSUE THREAD

**Issue by chrisxwan** [magus/react-native-facebook-login#26]
Followed the tutorial and used your code in the sample Toys project, but when I load React Native, I keep getting this error! It says it's coming from line 18 of FBLogin.ios.js

**Comment by magus** [comment]
Just updated to react-native 0.11 and updated the installation instructions. Verified everything works if you've followed the setup instructions. If you're still having the issue link me to the repository you're working with :)

**Comment by simchaWE** [comment]
I have the same issue with reacr 0.14.2

**Comment by timfpark** [comment]
I have the same issue with react 0.17

**Comment by magus** [comment]
I'll need something concrete like the application code to even begin to help with this sort of issue. If you follow the instructions things will work.

**Comment by timothytripp** [comment]
I was having the same problem and manually linking the libRCTFBLogin.a file (in Build Phases... Link Binary With Libraries) fixed it.  I'm not sure why the automatic native library linking with "rnpm link" didn't work but I definitely had to do this library manually.

**Comment by endotakashi1992** [comment]
@timothytripp
+1
Thanks. I was solved it.

**Comment by iamlacroix** [comment]
I experienced the same error even though I had followed the setup instructions correctly. Running `react-native run-ios` as mentioned in [this comment](https://github.com/magus/react-native-facebook-login/issues/110#issuecomment-236403744) did the trick: rebuilding in Xcode was not enough.

Wanted to mention it in case anyone else hits this issue.

**Comment by drewwells** [comment]
Seeing this on `"react-native": "^0.39.2",`, I can build in XCode but no number of `react-native run-ios` rebuilds are fixing it for the terminal.

**Comment by dutzi** [comment]
See my comment [here](https://github.com/fbsamples/f8app/issues/118#issuecomment-283670056), hope it helps

**Comment by MatthewJamesBoyle** [comment]
@dutzi  tried your idea, it doesnt fix it and im still facing the issue.

**Comment by BerndWessels** [comment]
Hi @timothytripp @magus
This still seems to be an issue in Android.
Do you know how to fix it for Android?

**Comment by AmitPandya007** [comment]
> I was having the same problem and manually linking the libRCTFBLogin.a file (in Build Phases... Link Binary With Libraries) fixed it. I'm not sure why the automatic native library linking with "rnpm link" didn't work but I definitely had to do this library manually.
> 
> BTW: This was using react-native 0.18.0rc

@timothytripp 
While adding libRCTFBLogin.a file manually, it is failing the build process with RCTBridge and RCTView errors. Any help will be really appreciated. Thank you.
